// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	_ "github.com/jackc/pgx/v5/stdlib"
)

// DatabaseMock implements mm_database.Database
type DatabaseMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcPing          func(ctx context.Context) (err error)
	funcPingOrigin    string
	inspectFuncPing   func(ctx context.Context)
	afterPingCounter  uint64
	beforePingCounter uint64
	PingMock          mDatabaseMockPing
}

// NewDatabaseMock returns a mock for mm_database.Database
func NewDatabaseMock(t minimock.Tester) *DatabaseMock {
	m := &DatabaseMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.PingMock = mDatabaseMockPing{mock: m}
	m.PingMock.callArgs = []*DatabaseMockPingParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mDatabaseMockPing struct {
	optional           bool
	mock               *DatabaseMock
	defaultExpectation *DatabaseMockPingExpectation
	expectations       []*DatabaseMockPingExpectation

	callArgs []*DatabaseMockPingParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// DatabaseMockPingExpectation specifies expectation struct of the Database.Ping
type DatabaseMockPingExpectation struct {
	mock               *DatabaseMock
	params             *DatabaseMockPingParams
	paramPtrs          *DatabaseMockPingParamPtrs
	expectationOrigins DatabaseMockPingExpectationOrigins
	results            *DatabaseMockPingResults
	returnOrigin       string
	Counter            uint64
}

// DatabaseMockPingParams contains parameters of the Database.Ping
type DatabaseMockPingParams struct {
	ctx context.Context
}

// DatabaseMockPingParamPtrs contains pointers to parameters of the Database.Ping
type DatabaseMockPingParamPtrs struct {
	ctx *context.Context
}

// DatabaseMockPingResults contains results of the Database.Ping
type DatabaseMockPingResults struct {
	err error
}

// DatabaseMockPingOrigins contains origins of expectations of the Database.Ping
type DatabaseMockPingExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPing *mDatabaseMockPing) Optional() *mDatabaseMockPing {
	mmPing.optional = true
	return mmPing
}

// Expect sets up expected params for Database.Ping
func (mmPing *mDatabaseMockPing) Expect(ctx context.Context) *mDatabaseMockPing {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("DatabaseMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &DatabaseMockPingExpectation{}
	}

	if mmPing.defaultExpectation.paramPtrs != nil {
		mmPing.mock.t.Fatalf("DatabaseMock.Ping mock is already set by ExpectParams functions")
	}

	mmPing.defaultExpectation.params = &DatabaseMockPingParams{ctx}
	mmPing.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPing.expectations {
		if minimock.Equal(e.params, mmPing.defaultExpectation.params) {
			mmPing.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPing.defaultExpectation.params)
		}
	}

	return mmPing
}

// ExpectCtxParam1 sets up expected param ctx for Database.Ping
func (mmPing *mDatabaseMockPing) ExpectCtxParam1(ctx context.Context) *mDatabaseMockPing {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("DatabaseMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &DatabaseMockPingExpectation{}
	}

	if mmPing.defaultExpectation.params != nil {
		mmPing.mock.t.Fatalf("DatabaseMock.Ping mock is already set by Expect")
	}

	if mmPing.defaultExpectation.paramPtrs == nil {
		mmPing.defaultExpectation.paramPtrs = &DatabaseMockPingParamPtrs{}
	}
	mmPing.defaultExpectation.paramPtrs.ctx = &ctx
	mmPing.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPing
}

// Inspect accepts an inspector function that has same arguments as the Database.Ping
func (mmPing *mDatabaseMockPing) Inspect(f func(ctx context.Context)) *mDatabaseMockPing {
	if mmPing.mock.inspectFuncPing != nil {
		mmPing.mock.t.Fatalf("Inspect function is already set for DatabaseMock.Ping")
	}

	mmPing.mock.inspectFuncPing = f

	return mmPing
}

// Return sets up results that will be returned by Database.Ping
func (mmPing *mDatabaseMockPing) Return(err error) *DatabaseMock {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("DatabaseMock.Ping mock is already set by Set")
	}

	if mmPing.defaultExpectation == nil {
		mmPing.defaultExpectation = &DatabaseMockPingExpectation{mock: mmPing.mock}
	}
	mmPing.defaultExpectation.results = &DatabaseMockPingResults{err}
	mmPing.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// Set uses given function f to mock the Database.Ping method
func (mmPing *mDatabaseMockPing) Set(f func(ctx context.Context) (err error)) *DatabaseMock {
	if mmPing.defaultExpectation != nil {
		mmPing.mock.t.Fatalf("Default expectation is already set for the Database.Ping method")
	}

	if len(mmPing.expectations) > 0 {
		mmPing.mock.t.Fatalf("Some expectations are already set for the Database.Ping method")
	}

	mmPing.mock.funcPing = f
	mmPing.mock.funcPingOrigin = minimock.CallerInfo(1)
	return mmPing.mock
}

// When sets expectation for the Database.Ping which will trigger the result defined by the following
// Then helper
func (mmPing *mDatabaseMockPing) When(ctx context.Context) *DatabaseMockPingExpectation {
	if mmPing.mock.funcPing != nil {
		mmPing.mock.t.Fatalf("DatabaseMock.Ping mock is already set by Set")
	}

	expectation := &DatabaseMockPingExpectation{
		mock:               mmPing.mock,
		params:             &DatabaseMockPingParams{ctx},
		expectationOrigins: DatabaseMockPingExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPing.expectations = append(mmPing.expectations, expectation)
	return expectation
}

// Then sets up Database.Ping return parameters for the expectation previously defined by the When method
func (e *DatabaseMockPingExpectation) Then(err error) *DatabaseMock {
	e.results = &DatabaseMockPingResults{err}
	return e.mock
}

// Times sets number of times Database.Ping should be invoked
func (mmPing *mDatabaseMockPing) Times(n uint64) *mDatabaseMockPing {
	if n == 0 {
		mmPing.mock.t.Fatalf("Times of DatabaseMock.Ping mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPing.expectedInvocations, n)
	mmPing.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPing
}

func (mmPing *mDatabaseMockPing) invocationsDone() bool {
	if len(mmPing.expectations) == 0 && mmPing.defaultExpectation == nil && mmPing.mock.funcPing == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPing.mock.afterPingCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPing.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Ping implements mm_database.Database
func (mmPing *DatabaseMock) Ping(ctx context.Context) (err error) {
	mm_atomic.AddUint64(&mmPing.beforePingCounter, 1)
	defer mm_atomic.AddUint64(&mmPing.afterPingCounter, 1)

	mmPing.t.Helper()

	if mmPing.inspectFuncPing != nil {
		mmPing.inspectFuncPing(ctx)
	}

	mm_params := DatabaseMockPingParams{ctx}

	// Record call args
	mmPing.PingMock.mutex.Lock()
	mmPing.PingMock.callArgs = append(mmPing.PingMock.callArgs, &mm_params)
	mmPing.PingMock.mutex.Unlock()

	for _, e := range mmPing.PingMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmPing.PingMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPing.PingMock.defaultExpectation.Counter, 1)
		mm_want := mmPing.PingMock.defaultExpectation.params
		mm_want_ptrs := mmPing.PingMock.defaultExpectation.paramPtrs

		mm_got := DatabaseMockPingParams{ctx}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPing.t.Errorf("DatabaseMock.Ping got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPing.PingMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPing.t.Errorf("DatabaseMock.Ping got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPing.PingMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPing.PingMock.defaultExpectation.results
		if mm_results == nil {
			mmPing.t.Fatal("No results are set for the DatabaseMock.Ping")
		}
		return (*mm_results).err
	}
	if mmPing.funcPing != nil {
		return mmPing.funcPing(ctx)
	}
	mmPing.t.Fatalf("Unexpected call to DatabaseMock.Ping. %v", ctx)
	return
}

// PingAfterCounter returns a count of finished DatabaseMock.Ping invocations
func (mmPing *DatabaseMock) PingAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.afterPingCounter)
}

// PingBeforeCounter returns a count of DatabaseMock.Ping invocations
func (mmPing *DatabaseMock) PingBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPing.beforePingCounter)
}

// Calls returns a list of arguments used in each call to DatabaseMock.Ping.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPing *mDatabaseMockPing) Calls() []*DatabaseMockPingParams {
	mmPing.mutex.RLock()

	argCopy := make([]*DatabaseMockPingParams, len(mmPing.callArgs))
	copy(argCopy, mmPing.callArgs)

	mmPing.mutex.RUnlock()

	return argCopy
}

// MinimockPingDone returns true if the count of the Ping invocations corresponds
// the number of defined expectations
func (m *DatabaseMock) MinimockPingDone() bool {
	if m.PingMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PingMock.invocationsDone()
}

// MinimockPingInspect logs each unmet expectation
func (m *DatabaseMock) MinimockPingInspect() {
	for _, e := range m.PingMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to DatabaseMock.Ping at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPingCounter := mm_atomic.LoadUint64(&m.afterPingCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PingMock.defaultExpectation != nil && afterPingCounter < 1 {
		if m.PingMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to DatabaseMock.Ping at\n%s", m.PingMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to DatabaseMock.Ping at\n%s with params: %#v", m.PingMock.defaultExpectation.expectationOrigins.origin, *m.PingMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPing != nil && afterPingCounter < 1 {
		m.t.Errorf("Expected call to DatabaseMock.Ping at\n%s", m.funcPingOrigin)
	}

	if !m.PingMock.invocationsDone() && afterPingCounter > 0 {
		m.t.Errorf("Expected %d calls to DatabaseMock.Ping at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PingMock.expectedInvocations), m.PingMock.expectedInvocationsOrigin, afterPingCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *DatabaseMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockPingInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *DatabaseMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *DatabaseMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockPingDone()
}
