// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetAuthToken provides a mock function for the type MockService
func (_mock *MockService) GetAuthToken(r *http.Request) (string, error) {
	ret := _mock.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (string, error)); ok {
		return returnFunc(r)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) string); ok {
		r0 = returnFunc(r)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(r)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthToken'
type MockService_GetAuthToken_Call struct {
	*mock.Call
}

// GetAuthToken is a helper method to define mock.On call
//   - r *http.Request
func (_e *MockService_Expecter) GetAuthToken(r interface{}) *MockService_GetAuthToken_Call {
	return &MockService_GetAuthToken_Call{Call: _e.mock.On("GetAuthToken", r)}
}

func (_c *MockService_GetAuthToken_Call) Run(run func(r *http.Request)) *MockService_GetAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetAuthToken_Call) Return(s string, err error) *MockService_GetAuthToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_GetAuthToken_Call) RunAndReturn(run func(r *http.Request) (string, error)) *MockService_GetAuthToken_Call {
	_c.Call.Return(run)
	return _c
}

// SetAuthToken provides a mock function for the type MockService
func (_mock *MockService) SetAuthToken(tokenString string, w http.ResponseWriter, r *http.Request) error {
	ret := _mock.Called(tokenString, w, r)

	if len(ret) == 0 {
		panic("no return value specified for SetAuthToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, http.ResponseWriter, *http.Request) error); ok {
		r0 = returnFunc(tokenString, w, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetAuthToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthToken'
type MockService_SetAuthToken_Call struct {
	*mock.Call
}

// SetAuthToken is a helper method to define mock.On call
//   - tokenString string
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockService_Expecter) SetAuthToken(tokenString interface{}, w interface{}, r interface{}) *MockService_SetAuthToken_Call {
	return &MockService_SetAuthToken_Call{Call: _e.mock.On("SetAuthToken", tokenString, w, r)}
}

func (_c *MockService_SetAuthToken_Call) Run(run func(tokenString string, w http.ResponseWriter, r *http.Request)) *MockService_SetAuthToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 http.ResponseWriter
		if args[1] != nil {
			arg1 = args[1].(http.ResponseWriter)
		}
		var arg2 *http.Request
		if args[2] != nil {
			arg2 = args[2].(*http.Request)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SetAuthToken_Call) Return(err error) *MockService_SetAuthToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetAuthToken_Call) RunAndReturn(run func(tokenString string, w http.ResponseWriter, r *http.Request) error) *MockService_SetAuthToken_Call {
	_c.Call.Return(run)
	return _c
}
