// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/shortlink/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortLinkRepository creates a new instance of MockShortLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkRepository {
	mock := &MockShortLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortLinkRepository is an autogenerated mock type for the ShortLinkRepository type
type MockShortLinkRepository struct {
	mock.Mock
}

type MockShortLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkRepository) EXPECT() *MockShortLinkRepository_Expecter {
	return &MockShortLinkRepository_Expecter{mock: &_m.Mock}
}

// DeleteByShortIDs provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) DeleteByShortIDs(ctx context.Context, shortIDs []string, userID *uuid.UUID) error {
	ret := _mock.Called(ctx, shortIDs, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByShortIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, shortIDs, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortLinkRepository_DeleteByShortIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByShortIDs'
type MockShortLinkRepository_DeleteByShortIDs_Call struct {
	*mock.Call
}

// DeleteByShortIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - shortIDs []string
//   - userID *uuid.UUID
func (_e *MockShortLinkRepository_Expecter) DeleteByShortIDs(ctx interface{}, shortIDs interface{}, userID interface{}) *MockShortLinkRepository_DeleteByShortIDs_Call {
	return &MockShortLinkRepository_DeleteByShortIDs_Call{Call: _e.mock.On("DeleteByShortIDs", ctx, shortIDs, userID)}
}

func (_c *MockShortLinkRepository_DeleteByShortIDs_Call) Run(run func(ctx context.Context, shortIDs []string, userID *uuid.UUID)) *MockShortLinkRepository_DeleteByShortIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_DeleteByShortIDs_Call) Return(err error) *MockShortLinkRepository_DeleteByShortIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortLinkRepository_DeleteByShortIDs_Call) RunAndReturn(run func(ctx context.Context, shortIDs []string, userID *uuid.UUID) error) *MockShortLinkRepository_DeleteByShortIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) Find(ctx context.Context, shortID string) (*model.ShortLink, error) {
	ret := _mock.Called(ctx, shortID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *model.ShortLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortLink, error)); ok {
		return returnFunc(ctx, shortID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortLink); ok {
		r0 = returnFunc(ctx, shortID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockShortLinkRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - shortID string
func (_e *MockShortLinkRepository_Expecter) Find(ctx interface{}, shortID interface{}) *MockShortLinkRepository_Find_Call {
	return &MockShortLinkRepository_Find_Call{Call: _e.mock.On("Find", ctx, shortID)}
}

func (_c *MockShortLinkRepository_Find_Call) Run(run func(ctx context.Context, shortID string)) *MockShortLinkRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_Find_Call) Return(shortLink *model.ShortLink, err error) *MockShortLinkRepository_Find_Call {
	_c.Call.Return(shortLink, err)
	return _c
}

func (_c *MockShortLinkRepository_Find_Call) RunAndReturn(run func(ctx context.Context, shortID string) (*model.ShortLink, error)) *MockShortLinkRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByURL provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) FindByURL(ctx context.Context, url string) (*model.ShortLink, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for FindByURL")
	}

	var r0 *model.ShortLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortLink, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortLink); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkRepository_FindByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByURL'
type MockShortLinkRepository_FindByURL_Call struct {
	*mock.Call
}

// FindByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockShortLinkRepository_Expecter) FindByURL(ctx interface{}, url interface{}) *MockShortLinkRepository_FindByURL_Call {
	return &MockShortLinkRepository_FindByURL_Call{Call: _e.mock.On("FindByURL", ctx, url)}
}

func (_c *MockShortLinkRepository_FindByURL_Call) Run(run func(ctx context.Context, url string)) *MockShortLinkRepository_FindByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_FindByURL_Call) Return(shortLink *model.ShortLink, err error) *MockShortLinkRepository_FindByURL_Call {
	_c.Call.Return(shortLink, err)
	return _c
}

func (_c *MockShortLinkRepository_FindByURL_Call) RunAndReturn(run func(ctx context.Context, url string) (*model.ShortLink, error)) *MockShortLinkRepository_FindByURL_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) FindByUserID(ctx context.Context, userID uuid.UUID) ([]model.ShortLink, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.ShortLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ShortLink, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ShortLink); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShortLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkRepository_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockShortLinkRepository_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockShortLinkRepository_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockShortLinkRepository_FindByUserID_Call {
	return &MockShortLinkRepository_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockShortLinkRepository_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockShortLinkRepository_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_FindByUserID_Call) Return(shortLinks []model.ShortLink, err error) *MockShortLinkRepository_FindByUserID_Call {
	_c.Call.Return(shortLinks, err)
	return _c
}

func (_c *MockShortLinkRepository_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]model.ShortLink, error)) *MockShortLinkRepository_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) Store(ctx context.Context, shortLink model.ShortLink, userID *uuid.UUID) error {
	ret := _mock.Called(ctx, shortLink, userID)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ShortLink, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, shortLink, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortLinkRepository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockShortLinkRepository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLink model.ShortLink
//   - userID *uuid.UUID
func (_e *MockShortLinkRepository_Expecter) Store(ctx interface{}, shortLink interface{}, userID interface{}) *MockShortLinkRepository_Store_Call {
	return &MockShortLinkRepository_Store_Call{Call: _e.mock.On("Store", ctx, shortLink, userID)}
}

func (_c *MockShortLinkRepository_Store_Call) Run(run func(ctx context.Context, shortLink model.ShortLink, userID *uuid.UUID)) *MockShortLinkRepository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ShortLink
		if args[1] != nil {
			arg1 = args[1].(model.ShortLink)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_Store_Call) Return(err error) *MockShortLinkRepository_Store_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortLinkRepository_Store_Call) RunAndReturn(run func(ctx context.Context, shortLink model.ShortLink, userID *uuid.UUID) error) *MockShortLinkRepository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// StoreAll provides a mock function for the type MockShortLinkRepository
func (_mock *MockShortLinkRepository) StoreAll(ctx context.Context, shortLinks []model.ShortLink, userID *uuid.UUID) error {
	ret := _mock.Called(ctx, shortLinks, userID)

	if len(ret) == 0 {
		panic("no return value specified for StoreAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []model.ShortLink, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, shortLinks, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortLinkRepository_StoreAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreAll'
type MockShortLinkRepository_StoreAll_Call struct {
	*mock.Call
}

// StoreAll is a helper method to define mock.On call
//   - ctx context.Context
//   - shortLinks []model.ShortLink
//   - userID *uuid.UUID
func (_e *MockShortLinkRepository_Expecter) StoreAll(ctx interface{}, shortLinks interface{}, userID interface{}) *MockShortLinkRepository_StoreAll_Call {
	return &MockShortLinkRepository_StoreAll_Call{Call: _e.mock.On("StoreAll", ctx, shortLinks, userID)}
}

func (_c *MockShortLinkRepository_StoreAll_Call) Run(run func(ctx context.Context, shortLinks []model.ShortLink, userID *uuid.UUID)) *MockShortLinkRepository_StoreAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []model.ShortLink
		if args[1] != nil {
			arg1 = args[1].([]model.ShortLink)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortLinkRepository_StoreAll_Call) Return(err error) *MockShortLinkRepository_StoreAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortLinkRepository_StoreAll_Call) RunAndReturn(run func(ctx context.Context, shortLinks []model.ShortLink, userID *uuid.UUID) error) *MockShortLinkRepository_StoreAll_Call {
	_c.Call.Return(run)
	return _c
}
