// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabaseHandler creates a new instance of MockDatabaseHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseHandler {
	mock := &MockDatabaseHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseHandler is an autogenerated mock type for the DatabaseHandler type
type MockDatabaseHandler struct {
	mock.Mock
}

type MockDatabaseHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseHandler) EXPECT() *MockDatabaseHandler_Expecter {
	return &MockDatabaseHandler_Expecter{mock: &_m.Mock}
}

// HandlePing provides a mock function for the type MockDatabaseHandler
func (_mock *MockDatabaseHandler) HandlePing(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockDatabaseHandler_HandlePing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandlePing'
type MockDatabaseHandler_HandlePing_Call struct {
	*mock.Call
}

// HandlePing is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockDatabaseHandler_Expecter) HandlePing(w interface{}, r interface{}) *MockDatabaseHandler_HandlePing_Call {
	return &MockDatabaseHandler_HandlePing_Call{Call: _e.mock.On("HandlePing", w, r)}
}

func (_c *MockDatabaseHandler_HandlePing_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockDatabaseHandler_HandlePing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseHandler_HandlePing_Call) Return() *MockDatabaseHandler_HandlePing_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDatabaseHandler_HandlePing_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockDatabaseHandler_HandlePing_Call {
	_c.Run(run)
	return _c
}
