// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShortLinkHandler creates a new instance of MockShortLinkHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkHandler {
	mock := &MockShortLinkHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortLinkHandler is an autogenerated mock type for the ShortLinkHandler type
type MockShortLinkHandler struct {
	mock.Mock
}

type MockShortLinkHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkHandler) EXPECT() *MockShortLinkHandler_Expecter {
	return &MockShortLinkHandler_Expecter{mock: &_m.Mock}
}

// HandleCreate provides a mock function for the type MockShortLinkHandler
func (_mock *MockShortLinkHandler) HandleCreate(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockShortLinkHandler_HandleCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCreate'
type MockShortLinkHandler_HandleCreate_Call struct {
	*mock.Call
}

// HandleCreate is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockShortLinkHandler_Expecter) HandleCreate(w interface{}, r interface{}) *MockShortLinkHandler_HandleCreate_Call {
	return &MockShortLinkHandler_HandleCreate_Call{Call: _e.mock.On("HandleCreate", w, r)}
}

func (_c *MockShortLinkHandler_HandleCreate_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkHandler_HandleCreate_Call) Return() *MockShortLinkHandler_HandleCreate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShortLinkHandler_HandleCreate_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleCreate_Call {
	_c.Run(run)
	return _c
}

// HandleCreateShorten provides a mock function for the type MockShortLinkHandler
func (_mock *MockShortLinkHandler) HandleCreateShorten(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockShortLinkHandler_HandleCreateShorten_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCreateShorten'
type MockShortLinkHandler_HandleCreateShorten_Call struct {
	*mock.Call
}

// HandleCreateShorten is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockShortLinkHandler_Expecter) HandleCreateShorten(w interface{}, r interface{}) *MockShortLinkHandler_HandleCreateShorten_Call {
	return &MockShortLinkHandler_HandleCreateShorten_Call{Call: _e.mock.On("HandleCreateShorten", w, r)}
}

func (_c *MockShortLinkHandler_HandleCreateShorten_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleCreateShorten_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkHandler_HandleCreateShorten_Call) Return() *MockShortLinkHandler_HandleCreateShorten_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShortLinkHandler_HandleCreateShorten_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleCreateShorten_Call {
	_c.Run(run)
	return _c
}

// HandleCreateShortenBatch provides a mock function for the type MockShortLinkHandler
func (_mock *MockShortLinkHandler) HandleCreateShortenBatch(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockShortLinkHandler_HandleCreateShortenBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCreateShortenBatch'
type MockShortLinkHandler_HandleCreateShortenBatch_Call struct {
	*mock.Call
}

// HandleCreateShortenBatch is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockShortLinkHandler_Expecter) HandleCreateShortenBatch(w interface{}, r interface{}) *MockShortLinkHandler_HandleCreateShortenBatch_Call {
	return &MockShortLinkHandler_HandleCreateShortenBatch_Call{Call: _e.mock.On("HandleCreateShortenBatch", w, r)}
}

func (_c *MockShortLinkHandler_HandleCreateShortenBatch_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleCreateShortenBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkHandler_HandleCreateShortenBatch_Call) Return() *MockShortLinkHandler_HandleCreateShortenBatch_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShortLinkHandler_HandleCreateShortenBatch_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleCreateShortenBatch_Call {
	_c.Run(run)
	return _c
}

// HandleDeleteUrls provides a mock function for the type MockShortLinkHandler
func (_mock *MockShortLinkHandler) HandleDeleteUrls(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockShortLinkHandler_HandleDeleteUrls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleDeleteUrls'
type MockShortLinkHandler_HandleDeleteUrls_Call struct {
	*mock.Call
}

// HandleDeleteUrls is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockShortLinkHandler_Expecter) HandleDeleteUrls(w interface{}, r interface{}) *MockShortLinkHandler_HandleDeleteUrls_Call {
	return &MockShortLinkHandler_HandleDeleteUrls_Call{Call: _e.mock.On("HandleDeleteUrls", w, r)}
}

func (_c *MockShortLinkHandler_HandleDeleteUrls_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleDeleteUrls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkHandler_HandleDeleteUrls_Call) Return() *MockShortLinkHandler_HandleDeleteUrls_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShortLinkHandler_HandleDeleteUrls_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleDeleteUrls_Call {
	_c.Run(run)
	return _c
}

// HandleGet provides a mock function for the type MockShortLinkHandler
func (_mock *MockShortLinkHandler) HandleGet(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockShortLinkHandler_HandleGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleGet'
type MockShortLinkHandler_HandleGet_Call struct {
	*mock.Call
}

// HandleGet is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockShortLinkHandler_Expecter) HandleGet(w interface{}, r interface{}) *MockShortLinkHandler_HandleGet_Call {
	return &MockShortLinkHandler_HandleGet_Call{Call: _e.mock.On("HandleGet", w, r)}
}

func (_c *MockShortLinkHandler_HandleGet_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkHandler_HandleGet_Call) Return() *MockShortLinkHandler_HandleGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShortLinkHandler_HandleGet_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleGet_Call {
	_c.Run(run)
	return _c
}

// HandleGetUserUrls provides a mock function for the type MockShortLinkHandler
func (_mock *MockShortLinkHandler) HandleGetUserUrls(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockShortLinkHandler_HandleGetUserUrls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleGetUserUrls'
type MockShortLinkHandler_HandleGetUserUrls_Call struct {
	*mock.Call
}

// HandleGetUserUrls is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockShortLinkHandler_Expecter) HandleGetUserUrls(w interface{}, r interface{}) *MockShortLinkHandler_HandleGetUserUrls_Call {
	return &MockShortLinkHandler_HandleGetUserUrls_Call{Call: _e.mock.On("HandleGetUserUrls", w, r)}
}

func (_c *MockShortLinkHandler_HandleGetUserUrls_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleGetUserUrls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkHandler_HandleGetUserUrls_Call) Return() *MockShortLinkHandler_HandleGetUserUrls_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockShortLinkHandler_HandleGetUserUrls_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockShortLinkHandler_HandleGetUserUrls_Call {
	_c.Run(run)
	return _c
}
