// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/shortlink/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortLinkProvider creates a new instance of MockShortLinkProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkProvider {
	mock := &MockShortLinkProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortLinkProvider is an autogenerated mock type for the ShortLinkProvider type
type MockShortLinkProvider struct {
	mock.Mock
}

type MockShortLinkProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkProvider) EXPECT() *MockShortLinkProvider_Expecter {
	return &MockShortLinkProvider_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockShortLinkProvider
func (_mock *MockShortLinkProvider) Find(ctx context.Context, shortID string) (*model.ShortLink, error) {
	ret := _mock.Called(ctx, shortID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *model.ShortLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortLink, error)); ok {
		return returnFunc(ctx, shortID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortLink); ok {
		r0 = returnFunc(ctx, shortID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkProvider_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockShortLinkProvider_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - shortID string
func (_e *MockShortLinkProvider_Expecter) Find(ctx interface{}, shortID interface{}) *MockShortLinkProvider_Find_Call {
	return &MockShortLinkProvider_Find_Call{Call: _e.mock.On("Find", ctx, shortID)}
}

func (_c *MockShortLinkProvider_Find_Call) Run(run func(ctx context.Context, shortID string)) *MockShortLinkProvider_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkProvider_Find_Call) Return(shortLink *model.ShortLink, err error) *MockShortLinkProvider_Find_Call {
	_c.Call.Return(shortLink, err)
	return _c
}

func (_c *MockShortLinkProvider_Find_Call) RunAndReturn(run func(ctx context.Context, shortID string) (*model.ShortLink, error)) *MockShortLinkProvider_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByURL provides a mock function for the type MockShortLinkProvider
func (_mock *MockShortLinkProvider) FindByURL(ctx context.Context, url string) (*model.ShortLink, error) {
	ret := _mock.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for FindByURL")
	}

	var r0 *model.ShortLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.ShortLink, error)); ok {
		return returnFunc(ctx, url)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.ShortLink); ok {
		r0 = returnFunc(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, url)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkProvider_FindByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByURL'
type MockShortLinkProvider_FindByURL_Call struct {
	*mock.Call
}

// FindByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *MockShortLinkProvider_Expecter) FindByURL(ctx interface{}, url interface{}) *MockShortLinkProvider_FindByURL_Call {
	return &MockShortLinkProvider_FindByURL_Call{Call: _e.mock.On("FindByURL", ctx, url)}
}

func (_c *MockShortLinkProvider_FindByURL_Call) Run(run func(ctx context.Context, url string)) *MockShortLinkProvider_FindByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkProvider_FindByURL_Call) Return(shortLink *model.ShortLink, err error) *MockShortLinkProvider_FindByURL_Call {
	_c.Call.Return(shortLink, err)
	return _c
}

func (_c *MockShortLinkProvider_FindByURL_Call) RunAndReturn(run func(ctx context.Context, url string) (*model.ShortLink, error)) *MockShortLinkProvider_FindByURL_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function for the type MockShortLinkProvider
func (_mock *MockShortLinkProvider) FindByUserID(ctx context.Context, userID uuid.UUID) ([]model.ShortLink, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []model.ShortLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.ShortLink, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.ShortLink); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShortLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkProvider_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockShortLinkProvider_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockShortLinkProvider_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockShortLinkProvider_FindByUserID_Call {
	return &MockShortLinkProvider_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockShortLinkProvider_FindByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockShortLinkProvider_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShortLinkProvider_FindByUserID_Call) Return(shortLinks []model.ShortLink, err error) *MockShortLinkProvider_FindByUserID_Call {
	_c.Call.Return(shortLinks, err)
	return _c
}

func (_c *MockShortLinkProvider_FindByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]model.ShortLink, error)) *MockShortLinkProvider_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}
