// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audit

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Notify(event Event) {
	_mock.Called(event)
	return
}

// MockPublisher_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockPublisher_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - event Event
func (_e *MockPublisher_Expecter) Notify(event interface{}) *MockPublisher_Notify_Call {
	return &MockPublisher_Notify_Call{Call: _e.mock.On("Notify", event)}
}

func (_c *MockPublisher_Notify_Call) Run(run func(event Event)) *MockPublisher_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Event
		if args[0] != nil {
			arg0 = args[0].(Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublisher_Notify_Call) Return() *MockPublisher_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_Notify_Call) RunAndReturn(run func(event Event)) *MockPublisher_Notify_Call {
	_c.Run(run)
	return _c
}

// Subscribe provides a mock function for the type MockPublisher
func (_mock *MockPublisher) Subscribe(observer Observer) {
	_mock.Called(observer)
	return
}

// MockPublisher_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockPublisher_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - observer Observer
func (_e *MockPublisher_Expecter) Subscribe(observer interface{}) *MockPublisher_Subscribe_Call {
	return &MockPublisher_Subscribe_Call{Call: _e.mock.On("Subscribe", observer)}
}

func (_c *MockPublisher_Subscribe_Call) Run(run func(observer Observer)) *MockPublisher_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Observer
		if args[0] != nil {
			arg0 = args[0].(Observer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPublisher_Subscribe_Call) Return() *MockPublisher_Subscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_Subscribe_Call) RunAndReturn(run func(observer Observer)) *MockPublisher_Subscribe_Call {
	_c.Run(run)
	return _c
}
