// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audit

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockObserver creates a new instance of MockObserver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObserver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObserver {
	mock := &MockObserver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObserver is an autogenerated mock type for the Observer type
type MockObserver struct {
	mock.Mock
}

type MockObserver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObserver) EXPECT() *MockObserver_Expecter {
	return &MockObserver_Expecter{mock: &_m.Mock}
}

// Update provides a mock function for the type MockObserver
func (_mock *MockObserver) Update(event Event) {
	_mock.Called(event)
	return
}

// MockObserver_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockObserver_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - event Event
func (_e *MockObserver_Expecter) Update(event interface{}) *MockObserver_Update_Call {
	return &MockObserver_Update_Call{Call: _e.mock.On("Update", event)}
}

func (_c *MockObserver_Update_Call) Run(run func(event Event)) *MockObserver_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Event
		if args[0] != nil {
			arg0 = args[0].(Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObserver_Update_Call) Return() *MockObserver_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockObserver_Update_Call) RunAndReturn(run func(event Event)) *MockObserver_Update_Call {
	_c.Run(run)
	return _c
}
