// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// NextID provides a mock function for the type MockUserService
func (_mock *MockUserService) NextID() uuid.UUID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextID")
	}

	var r0 uuid.UUID
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	return r0
}

// MockUserService_NextID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextID'
type MockUserService_NextID_Call struct {
	*mock.Call
}

// NextID is a helper method to define mock.On call
func (_e *MockUserService_Expecter) NextID() *MockUserService_NextID_Call {
	return &MockUserService_NextID_Call{Call: _e.mock.On("NextID")}
}

func (_c *MockUserService_NextID_Call) Run(run func()) *MockUserService_NextID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserService_NextID_Call) Return(uUID uuid.UUID) *MockUserService_NextID_Call {
	_c.Call.Return(uUID)
	return _c
}

func (_c *MockUserService_NextID_Call) RunAndReturn(run func() uuid.UUID) *MockUserService_NextID_Call {
	_c.Call.Return(run)
	return _c
}
