// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/google/uuid"
	"github.com/liebeSonne/shortlink/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortLinkService creates a new instance of MockShortLinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkService {
	mock := &MockShortLinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortLinkService is an autogenerated mock type for the ShortLinkService type
type MockShortLinkService struct {
	mock.Mock
}

type MockShortLinkService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkService) EXPECT() *MockShortLinkService_Expecter {
	return &MockShortLinkService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockShortLinkService
func (_mock *MockShortLinkService) Create(ctx context.Context, url string, userID *uuid.UUID) (*model.ShortLink, error) {
	ret := _mock.Called(ctx, url, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.ShortLink
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) (*model.ShortLink, error)); ok {
		return returnFunc(ctx, url, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) *model.ShortLink); ok {
		r0 = returnFunc(ctx, url, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShortLink)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, url, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockShortLinkService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - userID *uuid.UUID
func (_e *MockShortLinkService_Expecter) Create(ctx interface{}, url interface{}, userID interface{}) *MockShortLinkService_Create_Call {
	return &MockShortLinkService_Create_Call{Call: _e.mock.On("Create", ctx, url, userID)}
}

func (_c *MockShortLinkService_Create_Call) Run(run func(ctx context.Context, url string, userID *uuid.UUID)) *MockShortLinkService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortLinkService_Create_Call) Return(shortLink *model.ShortLink, err error) *MockShortLinkService_Create_Call {
	_c.Call.Return(shortLink, err)
	return _c
}

func (_c *MockShortLinkService_Create_Call) RunAndReturn(run func(ctx context.Context, url string, userID *uuid.UUID) (*model.ShortLink, error)) *MockShortLinkService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function for the type MockShortLinkService
func (_mock *MockShortLinkService) CreateBatch(ctx context.Context, urlsData []InputShortLinkData, userID *uuid.UUID) ([]OutputShortLinkData, error) {
	ret := _mock.Called(ctx, urlsData, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 []OutputShortLinkData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []InputShortLinkData, *uuid.UUID) ([]OutputShortLinkData, error)); ok {
		return returnFunc(ctx, urlsData, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []InputShortLinkData, *uuid.UUID) []OutputShortLinkData); ok {
		r0 = returnFunc(ctx, urlsData, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]OutputShortLinkData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []InputShortLinkData, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, urlsData, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShortLinkService_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockShortLinkService_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - urlsData []InputShortLinkData
//   - userID *uuid.UUID
func (_e *MockShortLinkService_Expecter) CreateBatch(ctx interface{}, urlsData interface{}, userID interface{}) *MockShortLinkService_CreateBatch_Call {
	return &MockShortLinkService_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, urlsData, userID)}
}

func (_c *MockShortLinkService_CreateBatch_Call) Run(run func(ctx context.Context, urlsData []InputShortLinkData, userID *uuid.UUID)) *MockShortLinkService_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []InputShortLinkData
		if args[1] != nil {
			arg1 = args[1].([]InputShortLinkData)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortLinkService_CreateBatch_Call) Return(outputShortLinkDatas []OutputShortLinkData, err error) *MockShortLinkService_CreateBatch_Call {
	_c.Call.Return(outputShortLinkDatas, err)
	return _c
}

func (_c *MockShortLinkService_CreateBatch_Call) RunAndReturn(run func(ctx context.Context, urlsData []InputShortLinkData, userID *uuid.UUID) ([]OutputShortLinkData, error)) *MockShortLinkService_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIDs provides a mock function for the type MockShortLinkService
func (_mock *MockShortLinkService) DeleteIDs(ctx context.Context, ids []string, userID *uuid.UUID) error {
	ret := _mock.Called(ctx, ids, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ids, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortLinkService_DeleteIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIDs'
type MockShortLinkService_DeleteIDs_Call struct {
	*mock.Call
}

// DeleteIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
//   - userID *uuid.UUID
func (_e *MockShortLinkService_Expecter) DeleteIDs(ctx interface{}, ids interface{}, userID interface{}) *MockShortLinkService_DeleteIDs_Call {
	return &MockShortLinkService_DeleteIDs_Call{Call: _e.mock.On("DeleteIDs", ctx, ids, userID)}
}

func (_c *MockShortLinkService_DeleteIDs_Call) Run(run func(ctx context.Context, ids []string, userID *uuid.UUID)) *MockShortLinkService_DeleteIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShortLinkService_DeleteIDs_Call) Return(err error) *MockShortLinkService_DeleteIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortLinkService_DeleteIDs_Call) RunAndReturn(run func(ctx context.Context, ids []string, userID *uuid.UUID) error) *MockShortLinkService_DeleteIDs_Call {
	_c.Call.Return(run)
	return _c
}
