// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortLinkDeleter creates a new instance of MockShortLinkDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortLinkDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortLinkDeleter {
	mock := &MockShortLinkDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortLinkDeleter is an autogenerated mock type for the ShortLinkDeleter type
type MockShortLinkDeleter struct {
	mock.Mock
}

type MockShortLinkDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortLinkDeleter) EXPECT() *MockShortLinkDeleter_Expecter {
	return &MockShortLinkDeleter_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockShortLinkDeleter
func (_mock *MockShortLinkDeleter) Add(input InputDelete) error {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(InputDelete) error); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShortLinkDeleter_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockShortLinkDeleter_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - input InputDelete
func (_e *MockShortLinkDeleter_Expecter) Add(input interface{}) *MockShortLinkDeleter_Add_Call {
	return &MockShortLinkDeleter_Add_Call{Call: _e.mock.On("Add", input)}
}

func (_c *MockShortLinkDeleter_Add_Call) Run(run func(input InputDelete)) *MockShortLinkDeleter_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 InputDelete
		if args[0] != nil {
			arg0 = args[0].(InputDelete)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortLinkDeleter_Add_Call) Return(err error) *MockShortLinkDeleter_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShortLinkDeleter_Add_Call) RunAndReturn(run func(input InputDelete) error) *MockShortLinkDeleter_Add_Call {
	_c.Call.Return(run)
	return _c
}
