// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockShortIDGenerator creates a new instance of MockShortIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShortIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShortIDGenerator {
	mock := &MockShortIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShortIDGenerator is an autogenerated mock type for the ShortIDGenerator type
type MockShortIDGenerator struct {
	mock.Mock
}

type MockShortIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShortIDGenerator) EXPECT() *MockShortIDGenerator_Expecter {
	return &MockShortIDGenerator_Expecter{mock: &_m.Mock}
}

// GenerateID provides a mock function for the type MockShortIDGenerator
func (_mock *MockShortIDGenerator) GenerateID(size uint) string {
	ret := _mock.Called(size)

	if len(ret) == 0 {
		panic("no return value specified for GenerateID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(uint) string); ok {
		r0 = returnFunc(size)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockShortIDGenerator_GenerateID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateID'
type MockShortIDGenerator_GenerateID_Call struct {
	*mock.Call
}

// GenerateID is a helper method to define mock.On call
//   - size uint
func (_e *MockShortIDGenerator_Expecter) GenerateID(size interface{}) *MockShortIDGenerator_GenerateID_Call {
	return &MockShortIDGenerator_GenerateID_Call{Call: _e.mock.On("GenerateID", size)}
}

func (_c *MockShortIDGenerator_GenerateID_Call) Run(run func(size uint)) *MockShortIDGenerator_GenerateID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint
		if args[0] != nil {
			arg0 = args[0].(uint)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShortIDGenerator_GenerateID_Call) Return(s string) *MockShortIDGenerator_GenerateID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockShortIDGenerator_GenerateID_Call) RunAndReturn(run func(size uint) string) *MockShortIDGenerator_GenerateID_Call {
	_c.Call.Return(run)
	return _c
}
