// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Create(tokenData Token) (string, error) {
	ret := _mock.Called(tokenData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Token) (string, error)); ok {
		return returnFunc(tokenData)
	}
	if returnFunc, ok := ret.Get(0).(func(Token) string); ok {
		r0 = returnFunc(tokenData)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(Token) error); ok {
		r1 = returnFunc(tokenData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - tokenData Token
func (_e *MockTokenService_Expecter) Create(tokenData interface{}) *MockTokenService_Create_Call {
	return &MockTokenService_Create_Call{Call: _e.mock.On("Create", tokenData)}
}

func (_c *MockTokenService_Create_Call) Run(run func(tokenData Token)) *MockTokenService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Token
		if args[0] != nil {
			arg0 = args[0].(Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_Create_Call) Return(s string, err error) *MockTokenService_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_Create_Call) RunAndReturn(run func(tokenData Token) (string, error)) *MockTokenService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Parse(tokenString string) (Token, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (Token, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) Token); ok {
		r0 = returnFunc(tokenString)
	} else {
		r0 = ret.Get(0).(Token)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockTokenService_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - tokenString string
func (_e *MockTokenService_Expecter) Parse(tokenString interface{}) *MockTokenService_Parse_Call {
	return &MockTokenService_Parse_Call{Call: _e.mock.On("Parse", tokenString)}
}

func (_c *MockTokenService_Parse_Call) Run(run func(tokenString string)) *MockTokenService_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_Parse_Call) Return(token Token, err error) *MockTokenService_Parse_Call {
	_c.Call.Return(token, err)
	return _c
}

func (_c *MockTokenService_Parse_Call) RunAndReturn(run func(tokenString string) (Token, error)) *MockTokenService_Parse_Call {
	_c.Call.Return(run)
	return _c
}
